# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Feature request
description: Let us know how we can make things better
title: "<productname>: <Your issue title>"
labels: ["priority: p3", "type: feature request", "triage me"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for stopping by to let us know something could be better!
        **PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
        **The issue you're having must be related to a file in this repository.** We are unable to provide assistance for issues unrelated to samples in this repository.
        Please include as much information as possible:
  - type: checkboxes
    id: language
    attributes:
      label: "Programming Language"
      options:
        - label: Go
        - label: Java        
        - label: Node.js
        - label: Python
        - label: Terraform
  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: proposal
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: markdown
    attributes:
      value: |      
        Making sure to follow these steps will guarantee the quickest resolution possible.
        Thanks!
